export { default as LandingPage } from './landing-page/Landing'
export { default as LoginPage } from './Auth-page/Login'
export { default as SignUpPage } from './Auth-page/SignUp'
export { default as SignUpInfoPage } from './Auth-page/SignUpInfo'
export { default as ForgetPaswordPage } from './Auth-page/ForgetPassword'
export { default as Home } from './home/Home'
export { default as Dashboard } from './dashboard/Dashboard'
export { default as Notification} from './notification/NotificationPage'
export { default as Profile} from './profile-page/ProfilePage'
export { default as DeviceRegister} from './register/DeviceRegister'
export { default as InstitutionRegister } from './register/InstituteRegister'