export { default as LandingPage } from './landing-page/Landing'
export { default as LoginPage } from './Auth-page/Login'
export { default as SignUpPage } from './Auth-page/SignUp'
export { default as SignUpInfoPage } from './Auth-page/SignUpInfo'
export { default as ForgetPaswordPage } from './Auth-page/ForgetPassword'